<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
    <Actions category="Scripts">
        <text>Filters Pie Menu</text>
        <Action name="trigger_filters_pie_menu">
            <icon></icon>
            <text>Filters Pie Menu</text>
            <whatsThis>Opens 8-sector Blender-style radial Filters Pie Menu for Krita adjustment filters.</whatsThis>
            <toolTip>Open Filters Pie Menu</toolTip>
            <iconText>FiltersPie</iconText>
            <activationFlags>10000</activationFlags>
            <shortcut>Space</shortcut>
            <isCheckable>false</isCheckable>
            <statusTip></statusTip>
        </Action>
    </Actions>
</ActionCollection>
